name: javascript-cucumber-esm-pnpm

env:
  ALLURE_ENDPOINT: https://demo.testops.cloud/
  ALLURE_PROJECT_ID: 4160
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
  ALLURE_RESULTS: "./out/allure-results"

on:
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: ALLURE_JOB_RUN_ID - service parameter (leave blank)
        required: false
      ALLURE_USERNAME:
        description: ALLURE_USERNAME - service parameter (leave blank)
        required: false
      BROWSER:
        required: true
        default: Google Chrome
      ENDPOINT: 
        required: true
        default: Demo
      OS:
        required: true
        default: macOS    
      VERSION:
        required: true
        default: '25.1.0'

permissions:
  contents: read
  actions: write

jobs:
  autotests:
    name: Run autotests
    runs-on: ubuntu-latest

    steps:
      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Clone repository
        uses: actions/checkout@v4.2.2

      - name: Set up Node 20
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20
          cache: pnpm

      - name: Install PNPM
        run: pnpm install

      - name: Get the latest allurectl
        run: |
          latest_version=$(curl -s https://api.github.com/repos/allure-framework/allurectl/releases/latest | jq -r .tag_name)
          echo "ALLURECTL_VERSION=$latest_version" >> $GITHUB_ENV

      - name: Install allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: https://demo.testops.cloud/
          allure-project-id: 4160
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allurectl-version: ${{ env.ALLURECTL_VERSION }}

      - name: Run autotests
        run: allurectl watch -- npm test
        env:
          ALLURE_LAUNCH_NAME: "Test Run #${{ github.run_number }}"
          ALLURE_RESULTS: "./out/allure-results"
          ALLURE_TESTPLAN_PATH: "./testplan.json"
          BRANCH: ${{ github.ref_name }}
          BROWSER: ${{ inputs.BROWSER }}
          ENDPOINT: ${{ inputs.ENDPOINT }}
          OS: ${{ inputs.OS }}
          VERSION: ${{ inputs.VERSION }}
